[".local/share/fonts/JetBrains/TrueType/JetBrainsMono Nerd Font"]
    type = "archive"
    url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
    exact = true

[".icons/OpenZone_White"]
    type = "archive"
    url = "file://{{ .chezmoi.sourceDir }}/files/encrypted_OpenZone_White.tar.xz.age"
    encrypted = true
    exact = true
    stripComponents = 1

[".chezmoiinstall/home_Alexx2000.asc"]
    type = "file"
    url = "https://download.opensuse.org/repositories/home:/Alexx2000:/doublecmd-svn/Debian_13/Release.key"

[".chezmoiinstall/suldr-keyring.asc"]
    type = "file"
    url = "file://{{ .chezmoi.sourceDir }}/files/suldr-keyring.asc"
    # url = "https://www.bchemnet.com/suldr/dists/debian/InRelease"

[".chezmoiinstall/90-corectrl.rules"]
    type = "file"
    url = "file://{{ .chezmoi.sourceDir }}/files/90-corectrl.rules"

[".chezmoiinstall/LG_UltraWide_34WP65G.icc"]
    type = "file"
    encrypted = true
    url = "file://{{ .chezmoi.sourceDir }}/files/encrypted_LG_UltraWide_34WP65G.icc.age"

[".chezmoiinstall/microsoft.asc"]
    type = "file"
    url = "https://packages.microsoft.com/keys/microsoft.asc"

[".chezmoiinstall/brave_browser_install.sh"]
    type = "file"
    url = "https://dl.brave.com/install.sh"

[".chezmoiinstall/teamviewer_amd64.deb"]
    type = "file"
    url = "https://download.teamviewer.com/download/linux/teamviewer_amd64.deb"

[".chezmoiinstall/oh-my-posh-install.sh"]
    type = "file"
    url = "https://ohmyposh.dev/install.sh"
