[".local/share/fonts/JetBrains/TrueType/JetBrainsMono Nerd Font"]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
exact = true
[".chezmoitmp/etc/apt/trusted.gpg.d/home_Alexx2000.asc"]
type = "file"
url = "https://download.opensuse.org/repositories/home:Alexx2000:doublecmd-svn/xUbuntu_24.10/Release.key"
