[jetbrainsmononerdfont]
type = "archive"
url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/JetBrainsMono.zip"
exact = true
stripComponents = 0
destination = "~/.local/share/fonts/JetBrains/TrueType"
